- analyses/cms-open-data-ttbar/coffea.ipynb
- datasets/cms-open-data-2015/branches.txt
Updating notebook to have two modes of execution: pure coffea and ServiceX+coffea. The ServiceX auto schema reproduces the AGC schema closely enough so the same processor can be used for both.
related: https://github.com/CoffeaTeam/coffea/issues/664, MET info cannot be easily fed through via ServiceX
> feat: add ServiceX+coffea option to notebook

- .gitignore
- workshops/agctools2022/statistical-inference/README.md
- workshops/agctools2022/statistical-inference/config/1Lbb.json
- workshops/agctools2022/statistical-inference/fit_funcx.py
- workshops/agctools2022/statistical-inference/requirements.txt
Resolves #33
This PR ports [an example](https://github.com/matthewfeickert/distributed-inference-with-pyhf-and-funcX) application of distributed inference with pyhf + funcX that can be demoed. This PR by itself should fulfill Issue #33 and will provide the input files for planned follow up PRs to add plotting of exclusion contour plots.
Additionally add stubs for pyhf and cabinetry tutorial sections that have yet to be written.
**Squash and merge commit message**
```
* Add pyhf + funcX example of distributed statistical inference for the published ATLAS
1Lbb SUSY analysis.
- c.f. https://www.hepdata.net/record/ins1755298
* Add requirements.txt for pyhf, cabinetry, and funcX
* Add pyhf and funcX related files to gitignore
* Add README with information and stubs for pyhf and funcX sections …
```
> feat: Add start of pyhf and funcX example

- workshops/agctools2022/statistical-inference/README.md
- workshops/agctools2022/statistical-inference/cabinetry-HEPData-workspace.ipynb
```
* Note in statistical-inference README that the cabinetry tutorials will be used
to cover material efficiently.
* Copy HEPData_workspace.ipynb from cabinetry tutorial but use the HEPData workspace used for
pyhf + funcX demonstration.
- c.f. https://www.hepdata.net/record/ins1755298
```
> feat: Use cabinetry tutorials but with ATLAS 139ifb 1Lbb workspace

- workshops/agctools2022/statistical-inference/plot-contour.ipynb
```
* Use requests to download the published plot figure as coffea-casa doesn't have
curl available to the users by default.
```
> fix: Use requests over curl for greater portability

- analyses/atlas-open-data-hzz/CoffeaHZZAnalysisWithServiceX.ipynb
The notebook now uses `vector` in the `calc_mllll` function. I wasn't able to run the notebook locally because of an error, but I am hoping that the function is correct. The function has been taken up from [this](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/master/13-TeV-examples/uproot_python/HZZAnalysis.ipynb) notebook. 
---
The error that I getting while running the notebook -
```
ServiceXException: (ServiceXException(...), 'Unable to find name/type uproot in api_endpoints in servicex.yaml configuration file. Saw only names (default, default) and types (xaod, cms_run1_aod)')
```
Full stack trace:
<details>
<summary>Trace:</summary>
```console
---------------------------------------------------------------------------
ServiceXException …
```
> Use `vector` in the HZZAnalysis notebook

- README.md
To clarify the various aspects of the AGC and hopefully also make it a bit more clear how this can be interesting to people outside of IRIS-HEP, this restructures the README a bit and adds additional information.
> docs: restructure readme

- README.md
With the first tag, we now have a Zenodo DOI: https://doi.org/10.5281/zenodo.7274936. Adding this to the readme.
> docs: add Zenodo DOI badge

- analyses/atlas-open-data-hzz/HZZ_analysis_pipeline.ipynb
- analyses/atlas-open-data-hzz/HZZ_analysis_pipeline.py
Adds names to the transforms performed by ServiceX.
> feat: ATLAS HZZ ServiceX transform names

- workshops/agctools2023/MLFlowExample.ipynb
- workshops/agctools2023/TritonExample.ipynb
- workshops/agctools2023/correctionlib_demo.ipynb
This PR introduces the Jupyter notebooks that were showcased for the 2023 AGC workshop in May. The workbooks were all committed in their un-evaluated state.
Indico link: [IRIS-HEP AGC workshop 2023](https://indico.cern.ch/event/1260431/timetable/?view=standard)
> docs: add notebooks used for AGC-2023 workshop

- README.md
- docs/index.rst
Updating RDF implementation links to the new website: https://github.com/root-project/analysis-grand-challenge.
> docs: update links for RDF implementation

- analyses/cms-open-data-ttbar/utils/__init__.py
This commits adds a new parameter to `utils.construct_fileset` called `local_data_cache`. If it is not None, it must be the path to a user-writable directory: `construct_fileset` will download any yet-not-present input files into that directory before returning a fileset that uses those local files.
Fixes #111  .
> feat: teach construct_fileset to cache remote files in local directory

- .github/workflows/CI.yml
- pyproject.toml
Depends on #148 , but since the only pending item in #148 is about a script in the `workshop` directory and we exclude that directory from the ruff check, #148 could also be merged as it is and it would make the linter check from this PR green.
> ci: add ruff linter check

- docs/taskbackground.rst
The task description used the wrong lower bin edge for the statistical inference step, this is fixed here.
resolves #161
> docs: fix binning for analysis task description

- analyses/cms-open-data-ttbar/validate_histograms.py
This is an attempt to address #168 . If adjacent bins are similar enough, the partial sum of the affected bins is compared. This will ensure that one event migrating across bins will not flag as an error. Maybe we can test this with RDF implementation (@andriiknu)
@alexander-held @eguiraud
> feat: updated validation script to check partial bin sums

- docs/taskbackground.rst
- docs/versionsdescription.rst
As per suggestion by @alexander-held and @eguiraud, the table in the documentation for the different AGC versions is broken into two: one for differences in task (0, 1, and 2 as of now) and another for differences in implementation.
> docs: updated version documentation

- analyses/cms-open-data-ttbar/validate_histograms.py
These histograms are needed for the statistical inference stage, but they are built from other histograms and it is up to the implementation whether to write out dedicated pseudodata histograms or build them on the fly.
If approved I'll backport to the v1 branch.
> feat: do not require pseudodata hists in validate_histograms.py

- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.ipynb
- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py
Fixes cut values during histogram re-binning to correspond to actual bin edges. This does not change functionality but is a more natural and readable way to specify the operation.
Thanks to @eguiraud for spotting!
> fix: set bin edge cuts to 110 GeV instead of 120 GeV

- docs/taskbackground.rst
- docs/versionsdescription.rst
Adding a description of the v1.2 tag, fixing the jet eta cut and explaining how to obtain the tight lepton veto via the variable provided in the input files. Also clarify how to pick jets for the ML part if not considering all permutations.
> docs: add v1.2 description and fix cut descriptions

- docs/index.rst
Extends #183 to also list the implementation under https://agc.readthedocs.io/.
> docs: add columnflow implementation to readthedocs

- analyses/cms-open-data-ttbar/config.yaml
- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.ipynb
- analyses/cms-open-data-ttbar/utils/__init__.py
This adds a config option `INPUT_FROM_EOS` to the `config.yaml`. It switches the input from https at UNL to xrootd at CERN's EOS.
related: #128
> feat: support input files on public EOS

- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.ipynb
- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py
- analyses/cms-open-data-ttbar/utils/config.py
This extends #189 to store the xcache prefix setting in the benchmarking config.
> feat: move xcache prefix setting to config

- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.ipynb
- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py
- analyses/cms-open-data-ttbar/utils/__init__.py
This ports #167 back to the AGC v1 branch. The solution here is likely not very stable and needs to be replaced with something better in the long term. It relies on splitting at the port, which seems to work in practice. This may change with other xcache setups and require additional updates then.
Also including another small fix: do not override `config` by the cabinetry configuration (matters when re-running parts of the notebook).
> fix: handle long file names in ServiceX dataset grouping (AGC v1)

- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.ipynb
- analyses/cms-open-data-ttbar/ttbar_analysis_pipeline.py
- analyses/cms-open-data-ttbar/utils/file_input.py
This allows using `root://` instead of just https. In practice, the problem seems to be that some parent paths have a different format that expected. This was tested at the UChicago AF. A standard path looks like this
```
root:::xcache.af.uchicago.edu:1094::root:::xrootd-local.unl.edu:1094::store:user:AGC:nanoAOD:TT_TuneCUETP8M1_13TeV-powheg-pythia8:cmsopendata2015_ttbar_19980_PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1_00000_0000.root
```
while some paths instead look like the following:
```
_0550680f54153965e73292ef2c94b7a94dc4a8f5edu:1094::store:user:AGC:nanoAOD:ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1:cmsopendata2015_single_top_t_chan_19408_PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1_00000_0006.root
```
Using the same approach as in the …
> fix: make ServiceX dataset grouping compatible with root protocol

- analyses/cms-open-data-ttbar/utils/clients.py
- analyses/cms-open-data-ttbar/utils/config.py
@oshadura @alexander-held following up on our chat last month:
This PR adds an option to run CMS OpenData workflow at Purdue Analysis Facility via Dask Gateway cluster.
The setup is similar to the `cmsaf-dev` option, the only differences are:
- The address of the Dask Gateway API server;
- The default number of workers is 10 to avoid using too much resources when running AGC as a "smoke test".
Additional info about the Dask Gateway setup at Purdue AF can be found [here](https://analysis-facility.physics.purdue.edu/en/latest/doc-dask-gateway.html). At Purdue AF, we have two Dask Gateway instances - with SLURM and Kubernetes backends. The `purdue-af` AGC client will use the Kubernetes backend.
> feat: add a client for Purdue Analysis Facility

- .gitattributes
- .gitignore
- analyses/cms-open-data-ttbar/README.md
- pixi.lock
- pixi.toml
* Resolves #199 
* Resolves #144
* Resolves #140
---
* Add `pixi` manifest (`pixi.toml`) and `pixi` lockfile (`pixi.lock`) to fully specify the project dependencies. This provides a multi-environment multi-platform (Linux, macOS) lockfile.
* In addition to the default feature, add `latest`, `cms-open-data-ttbar`, and `local` pixi features and corresponding environments composed from the features. The `cms-open-data-ttbar` feature is designed to be compatible with the Coffea Base image which uses SemVer `coffea` (Coffea-casa build with coffea 0.7.21/dask 2022.05.0/HTCondor and cheese).
- The `cms-open-data-ttbar` feature has an `install-ipykernel` task that installs a kernel such that the pixi environment can be used on a coffea-casa instance from a notebook.
- The local features have the …
> feat: Add pixi project configuration
